version: '3'
services:
    mmiab:
        depends_on:
            - redis
        restart: always
        build: .
        ports:
            - "5000:5000"
        expose:
            - "5000"
        volumes:
        
            - ./monolith/db:/code/monolith/db
            #docker sets the timezone to UTC by default, this (ugly) fix makes sure that the timezone of the
            # celery workers is the same as the host
            # In the future we should handle conversions of timezones and not mounting the  etc/timezone volume
            - /etc/localtime:/etc/localtime:ro 
    celery:
        depends_on:
            - redis
            - mmiab
        build: .
        restart: always
        command: bash ./celery.sh
        links:
            -  redis
        volumes:
            - ./monolith/db:/code/monolith/db
            # see mmiab volumes
            - /etc/localtime:/etc/localtime:ro

    redis:
        image: "redis:alpine"
        container_name: rd01
        restart: on-failure
        expose:
            - "6379"