"""new shcema

Revision ID: 3989e623ee0f
Revises: 
Create Date: 2021-11-09 22:10:28.373183

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "3989e623ee0f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "is_notified_sender")
    op.drop_column("message", "is_notified_receipent")
    op.add_column("notify", sa.Column("id_message", sa.Integer(), nullable=True))
    op.add_column("notify", sa.Column("id_user", sa.Integer(), nullable=True))
    op.add_column("notify", sa.Column("is_notified", sa.Boolean(), nullable=True))
    op.add_column("notify", sa.Column("for_recipient", sa.Boolean(), nullable=True))
    op.add_column("notify", sa.Column("for_sender", sa.Boolean(), nullable=True))
    op.add_column("notify", sa.Column("for_lottery", sa.Boolean(), nullable=True))
    op.add_column("notify", sa.Column("from_recipient", sa.Integer(), nullable=True))
    op.drop_column("notify", "receipent_notified")
    op.drop_column("notify", "id_sender")
    op.drop_column("notify", "sender_notified")
    op.drop_column("notify", "id_receipent")
    op.add_column("recipient", sa.Column("has_opened", sa.Boolean(), nullable=True))
    op.drop_column("recipient", "is_notified")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipient", sa.Column("is_notified", sa.BOOLEAN(), nullable=True))
    op.drop_column("recipient", "has_opened")
    op.add_column("notify", sa.Column("id_receipent", sa.INTEGER(), nullable=True))
    op.add_column("notify", sa.Column("sender_notified", sa.BOOLEAN(), nullable=True))
    op.add_column("notify", sa.Column("id_sender", sa.INTEGER(), nullable=True))
    op.add_column(
        "notify", sa.Column("receipent_notified", sa.BOOLEAN(), nullable=True)
    )
    op.drop_column("notify", "from_recipient")
    op.drop_column("notify", "for_lottery")
    op.drop_column("notify", "for_sender")
    op.drop_column("notify", "for_recipient")
    op.drop_column("notify", "is_notified")
    op.drop_column("notify", "id_user")
    op.drop_column("notify", "id_message")
    op.add_column(
        "message", sa.Column("is_notified_receipent", sa.BOOLEAN(), nullable=True)
    )
    op.add_column(
        "message", sa.Column("is_notified_sender", sa.BOOLEAN(), nullable=True)
    )
    # ### end Alembic commands ###
