"""new column

Revision ID: b8ba3e038c09
Revises: 3989e623ee0f
Create Date: 2021-11-10 09:41:54.873932

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b8ba3e038c09"
down_revision = "3989e623ee0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipient", sa.Column("read_deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipient", "read_deleted")
    # ### end Alembic commands ###
